version: "3"

services:
  web:
    image: nginx
    restart: always
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - /Users/xuzhixuan/Documents/workspace/blog-be:/var/www/html
    networks:
      web:
        ipv4_address: 172.19.0.4
      fpm:

  app:
    build: .
    restart: always
    volumes:
      - /Users/xuzhixuan/Documents/workspace/blog-be:/var/www/html    
    networks:
      - database
      - fpm

networks:
  database:
    external: true
  web:
    external: true
  fpm:
    driver: bridge