version: "3"

services:
  httpd:
    image: nginx
    container_name: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      web:
        ipv4_address: 172.19.0.2

networks:
  web:
    external: true